import React, {useState} from 'react';
import {CheckCircle2, Send} from 'lucide-react';
import {CMSPageRenderer} from '../components/CMSPageRenderer';
import {submitContact} from '../lib/publicApi';
import {ServiceType} from '../types';

export const CMSContactPage:React.FC=()=>{
 const [form,setForm]=useState({name:'',phone:'',email:'',service:'student_loan' as ServiceType,message:''});
 const [sending,setSending]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSending(true);setError('');try{await submitContact(form);setDone(true)}catch(err){setError(err instanceof Error?err.message:'Unable to send your enquiry right now.')}finally{setSending(false)}};
 return <div><CMSPageRenderer slug="contact"/><section className="bg-[#f6f8fc] py-16 lg:py-20"><div className="max-w-4xl mx-auto px-5 lg:px-8"><div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-9 shadow-sm">{done?<div className="py-12 text-center"><div className="w-14 h-14 mx-auto rounded-full bg-[#e3fff2] text-[#0d0a64] grid place-items-center"><CheckCircle2/></div><h2 className="mt-5 text-2xl font-extrabold text-[#0d0a64]">Enquiry received</h2><p className="mt-3 text-sm text-slate-500">Thank you. Our team will review your message and respond using the contact details provided.</p><button onClick={()=>{setDone(false);setForm({name:'',phone:'',email:'',service:'student_loan',message:''})}} className="mt-6 text-xs font-bold text-[#e7020b]">Send another enquiry</button></div>:<form onSubmit={submit} className="space-y-5"><div><div className="text-[10px] tracking-[.2em] uppercase font-extrabold text-[#e7020b]">ENQUIRY FORM</div><h2 className="mt-2 text-2xl font-extrabold text-[#0d0a64]">Tell us what you need</h2><p className="mt-2 text-xs text-slate-500">Provide the basics and our team will guide you to the appropriate next step.</p></div><div className="grid sm:grid-cols-2 gap-4"><Input label="Full name" required value={form.name} onChange={v=>setForm({...form,name:v})}/><Input label="Phone / WhatsApp" required value={form.phone} onChange={v=>setForm({...form,phone:v})}/><Input label="Email" type="email" value={form.email} onChange={v=>setForm({...form,email:v})}/><label className="block"><span className="block text-[10px] uppercase tracking-wider text-slate-400 font-bold mb-1.5">Service</span><select value={form.service} onChange={e=>setForm({...form,service:e.target.value as ServiceType})} className="w-full border border-slate-200 rounded-xl px-3 py-3 text-xs outline-none focus:border-[#e7020b]"><option value="student_loan">Student financing</option><option value="investment">Investment</option><option value="business">Business financing</option><option value="personal">Personal finance</option><option value="other">Other enquiry</option></select></label></div><label className="block"><span className="block text-[10px] uppercase tracking-wider text-slate-400 font-bold mb-1.5">Message</span><textarea required rows={6} value={form.message} onChange={e=>setForm({...form,message:e.target.value})} className="w-full border border-slate-200 rounded-xl px-3 py-3 text-xs outline-none focus:border-[#e7020b] resize-none" placeholder="Briefly tell us about your requirement…"/></label>{error&&<div className="p-3 rounded-xl bg-red-50 border border-red-200 text-xs text-red-700">{error}</div>}<div className="flex justify-end"><button disabled={sending} className="inline-flex items-center gap-2 bg-[#e7020b] text-white px-5 py-3 rounded-xl text-xs font-extrabold disabled:opacity-50"><Send className="w-4 h-4"/>{sending?'Sending…':'Send enquiry'}</button></div></form>}</div></div></section></div>
}
function Input({label,value,onChange,required=false,type='text'}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean;type?:string}){return <label className="block"><span className="block text-[10px] uppercase tracking-wider text-slate-400 font-bold mb-1.5">{label}</span><input type={type} required={required} value={value} onChange={e=>onChange(e.target.value)} className="w-full border border-slate-200 rounded-xl px-3 py-3 text-xs outline-none focus:border-[#e7020b]"/></label>}
