import React, { useMemo, useState } from 'react';
import { ArrowRight, Check, ChevronDown, Clock3, Mail, MapPin, Phone, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useContent } from '../context/ContentContext';
import heroDefaultImage from '../assets/images/nigerian_businesswoman_hero_1790205199974.webp';
import graduateDefaultImage from '../assets/images/nigerian_graduate_success_1790142702336.webp';
import meetingDefaultImage from '../assets/images/african_investment_meeting_1790151240660.webp';
import businessDefaultImage from '../assets/images/business_financing_growth_1790141424769.webp';
import professionalDefaultImage from '../assets/images/nigerian_professional_hero_1790151218863.webp';
import { PageLoader } from './PageLoader';

type Section = { id:string; section_key:string; label:string; section_type:string; background:string; content:any; is_enabled:boolean; display_order:number };
type Page = { id:string; slug:string; title:string; status:string; seo_title?:string|null; seo_description?:string|null };

const bg = (name:string) => name==='navy'?'bg-[#0d0a64] text-white':name==='mint'?'bg-[#e3fff2] text-[#17202A]':name==='soft'?'bg-[#f6f8fc] text-[#17202A]':'bg-white text-[#17202A]';
const ButtonLink=({href,children,secondary=false}:{href:string;children:React.ReactNode;secondary?:boolean})=><Link to={href} className={`inline-flex items-center gap-2 rounded-xl px-5 py-3 text-xs font-extrabold uppercase tracking-wide transition ${secondary?'border border-white/30 text-white hover:bg-white/10':'bg-[#e7020b] text-white hover:translate-y-[-1px]'}`}>{children}<ArrowRight className="w-4 h-4"/></Link>;

function Hero({c,bgName}:{c:any;bgName:string}){return <section className={`${bg(bgName)} relative overflow-hidden`}><div className="absolute -right-24 -top-28 w-80 h-80 rounded-full bg-[#e7020b]/10 blur-3xl"/><div className="max-w-7xl mx-auto px-5 lg:px-8 py-20 lg:py-28 grid lg:grid-cols-[1.05fr_.95fr] gap-12 items-center relative"><div><div className="text-[10px] font-extrabold tracking-[.24em] uppercase text-[#e7020b] mb-5">{c.eyebrow}</div><h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold leading-[1.03] max-w-3xl">{c.heading}</h1><p className={`mt-6 text-base lg:text-lg leading-8 max-w-2xl ${bgName==='navy'?'text-white/70':'text-slate-600'}`}>{c.description}</p><div className="mt-8 flex flex-wrap gap-3">{c.primaryCta&&<ButtonLink href={c.primaryHref||'/apply'}>{c.primaryCta}</ButtonLink>}{c.secondaryCta&&<ButtonLink href={c.secondaryHref||'/contact'} secondary>{c.secondaryCta}</ButtonLink>}</div></div><div className="relative"><div className="aspect-[4/3] rounded-[2rem] overflow-hidden bg-white/10 border border-white/10 shadow-2xl"><img src={c.imageUrl||heroDefaultImage.src} alt="" className="w-full h-full object-cover" onError={(e)=>{(e.currentTarget as HTMLImageElement).style.display='none'}}/><div className="absolute inset-0 bg-gradient-to-tr from-[#0d0a64]/30 to-transparent"/></div><div className="absolute -bottom-5 -left-5 bg-white text-[#0d0a64] rounded-2xl shadow-xl px-5 py-4 flex items-center gap-3"><ShieldCheck className="w-5 h-5 text-[#e7020b]"/><div><div className="text-xs font-extrabold">Structured. Clear. Human.</div><div className="text-[10px] text-slate-400">Finance with purpose</div></div></div></div></div></section>}
function Trust({c}:{c:any}){return <section className="bg-[#e3fff2] border-y border-[#0d0a64]/5"><div className="max-w-7xl mx-auto px-5 lg:px-8 py-5 grid grid-cols-2 md:grid-cols-4 gap-4">{(c.items||[]).map((x:any)=><div key={typeof x==='string'?x:x.value} className="flex items-center justify-center gap-2 text-[10px] font-extrabold uppercase tracking-wide text-[#0d0a64]"><Check className="w-4 h-4 text-[#e7020b]"/>{typeof x==='string'?x:x.value}</div>)}</div></section>}
function Split({c}:{c:any}){return <section className="max-w-7xl mx-auto px-5 lg:px-8 py-20 lg:py-24 grid lg:grid-cols-2 gap-12 items-center"><div>{c.eyebrow&&<div className="text-[10px] tracking-[.2em] font-extrabold uppercase text-[#e7020b]">{c.eyebrow}</div>}<h2 className="mt-3 text-3xl lg:text-4xl font-extrabold text-[#0d0a64]">{c.heading}</h2><p className="mt-5 text-sm lg:text-base leading-7 text-slate-600">{c.description}</p><div className="mt-7 grid sm:grid-cols-2 gap-3">{(c.points||[]).map((p:any)=><div key={typeof p==='string'?p:p.value} className="flex gap-3 p-4 rounded-xl bg-[#f6f8fc]"><Check className="w-4 h-4 text-[#e7020b] mt-0.5"/><span className="text-xs font-bold text-[#0d0a64]">{typeof p==='string'?p:p.value}</span></div>)}</div></div><div className="rounded-[2rem] bg-[#0d0a64] min-h-[360px] overflow-hidden relative"><img src={c.imageUrl||''} alt="" className="w-full h-full object-cover" onError={(e)=>{(e.currentTarget as HTMLImageElement).style.display='none'}}/><div className="absolute inset-0 bg-gradient-to-br from-[#0d0a64]/20 to-[#0d0a64]/90"/><div className="absolute left-7 bottom-7 text-white max-w-sm"><div className="text-[10px] uppercase tracking-[.2em] text-white/50">EMUNAHH-INVEST</div><div className="text-2xl font-extrabold mt-2">Finance that moves with your goals.</div></div></div></section>}
function Cards({c}:{c:any}){return <section className="max-w-7xl mx-auto px-5 lg:px-8 py-20"><div className="max-w-2xl"><div className="text-[10px] tracking-[.2em] font-extrabold uppercase text-[#e7020b]">{c.eyebrow}</div><h2 className="mt-3 text-3xl lg:text-4xl font-extrabold text-[#0d0a64]">{c.heading}</h2><p className="mt-4 text-sm text-slate-500 leading-7">{c.description}</p></div><div className="mt-10 grid md:grid-cols-2 lg:grid-cols-4 gap-4">{(c.items||[]).map((x:any,i:number)=><div key={i} className="group bg-white border border-slate-200 rounded-2xl p-6 hover:border-[#0d0a64]/20 hover:shadow-xl transition"><div className="w-10 h-10 rounded-xl bg-[#e3fff2] text-[#0d0a64] grid place-items-center text-xs font-extrabold">0{i+1}</div><h3 className="mt-6 text-base font-extrabold text-[#0d0a64]">{x.title}</h3><p className="mt-3 text-xs leading-6 text-slate-500">{x.description}</p>{x.href&&<Link to={x.href} className="inline-flex mt-5 text-[10px] font-extrabold uppercase text-[#e7020b]">{x.cta||'Learn more'} <ArrowRight className="w-3.5 h-3.5 ml-1"/></Link>}</div>)}</div></section>}
function Features({c}:{c:any}){return <section className="max-w-7xl mx-auto px-5 lg:px-8 py-20"><div className="max-w-2xl"><div className="text-[10px] tracking-[.2em] font-extrabold uppercase text-[#e7020b]">{c.eyebrow}</div><h2 className="mt-3 text-3xl font-extrabold text-[#0d0a64]">{c.heading}</h2></div><div className="mt-10 grid md:grid-cols-2 lg:grid-cols-4 gap-4">{(c.items||[]).map((x:any,i:number)=><div key={i} className="p-6 rounded-2xl bg-white border border-slate-200"><div className="w-9 h-9 rounded-full bg-[#0d0a64] text-white grid place-items-center text-xs font-bold">{i+1}</div><h3 className="mt-5 font-extrabold text-[#0d0a64]">{x.title}</h3><p className="mt-2 text-xs leading-6 text-slate-500">{x.description}</p></div>)}</div></section>}
function Steps({c}:{c:any}){return <section className="bg-[#f6f8fc] py-20"><div className="max-w-7xl mx-auto px-5 lg:px-8"><div className="max-w-2xl"><div className="text-[10px] tracking-[.2em] font-extrabold uppercase text-[#e7020b]">{c.eyebrow}</div><h2 className="mt-3 text-3xl font-extrabold text-[#0d0a64]">{c.heading}</h2></div><div className="mt-10 grid md:grid-cols-4 gap-4">{(c.steps||[]).map((x:any)=><div key={x.number} className="bg-white rounded-2xl p-6 border border-slate-200"><div className="text-2xl font-black text-[#e7020b]">{x.number}</div><h3 className="mt-5 font-extrabold text-[#0d0a64]">{x.title}</h3><p className="mt-2 text-xs leading-6 text-slate-500">{x.description}</p></div>)}</div></div></section>}
function FAQ({c}:{c:any}){const [open,setOpen]=useState<number|null>(null);return <section className="max-w-4xl mx-auto px-5 py-20"><div className="text-center"><div className="text-[10px] tracking-[.2em] font-extrabold uppercase text-[#e7020b]">FAQ</div><h2 className="mt-3 text-3xl font-extrabold text-[#0d0a64]">{c.heading||'Frequently asked questions'}</h2></div><div className="mt-10 divide-y border-y border-slate-200">{(c.items||[]).map((x:any,i:number)=><button key={i} onClick={()=>setOpen(open===i?null:i)} className="w-full py-5 text-left flex justify-between gap-6"><span className="font-bold text-sm text-[#0d0a64]">{x.question}</span><ChevronDown className={`w-4 h-4 text-[#e7020b] transition ${open===i?'rotate-180':''}`}/>{open===i&&<span className="absolute"/>}<div className="sr-only">{x.answer}</div></button>)}<div>{open!==null&&(c.items||[])[open]&&<div className="pb-5 text-xs leading-6 text-slate-500">{(c.items||[])[open].answer}</div>}</div></div></section>}
function CTA({c}:{c:any}){return <section className="bg-[#0d0a64] text-white"><div className="max-w-7xl mx-auto px-5 lg:px-8 py-16 flex flex-col md:flex-row md:items-center justify-between gap-8"><div><h2 className="text-3xl font-extrabold">{c.heading}</h2><p className="mt-3 text-sm text-white/65 max-w-2xl">{c.description}</p></div><ButtonLink href={c.href||'/contact'}>{c.buttonText||'Get started'}</ButtonLink></div></section>}
function ContactBlock({c}:{c:any}){return <section className="max-w-7xl mx-auto px-5 lg:px-8 py-20"><div className="grid md:grid-cols-3 gap-4"><div className="p-6 rounded-2xl bg-[#f6f8fc]"><MapPin className="w-5 h-5 text-[#e7020b]"/><h3 className="mt-4 font-extrabold text-[#0d0a64]">Office</h3><p className="mt-2 text-xs leading-6 text-slate-500">{c.description}</p></div><div className="p-6 rounded-2xl bg-[#f6f8fc]"><Phone className="w-5 h-5 text-[#e7020b]"/><h3 className="mt-4 font-extrabold text-[#0d0a64]">Phone</h3><p className="mt-2 text-xs text-slate-500">{c.phone}</p></div><div className="p-6 rounded-2xl bg-[#f6f8fc]"><Mail className="w-5 h-5 text-[#e7020b]"/><h3 className="mt-4 font-extrabold text-[#0d0a64]">Email</h3><p className="mt-2 text-xs text-slate-500">{c.email}</p><div className="mt-3 text-[10px] text-slate-400 flex gap-2"><Clock3 className="w-3.5 h-3.5"/>{c.hours}</div></div></div></section>}
function Legal({c}:{c:any}){return <section className="max-w-4xl mx-auto px-5 lg:px-8 py-20"><div className="space-y-10">{(c.sections||[]).map((x:any)=><article key={x.title}><h2 className="text-xl font-extrabold text-[#0d0a64]">{x.title}</h2><p className="mt-3 text-sm leading-8 text-slate-600">{x.body}</p></article>)}</div></section>}

export function CMSPageRenderer({slug}:{slug:string}){const {cmsPages,cmsSections,isLoading}=useContent() as any;const page:Page|undefined=useMemo(()=>cmsPages?.find((p:Page)=>p.slug===slug),[cmsPages,slug]);const sections:Section[]=useMemo(()=>cmsSections?.filter((s:Section)=>s.page_id===page?.id&&s.is_enabled).sort((a:Section,b:Section)=>a.display_order-b.display_order)||[],[cmsSections,page]);if(isLoading&&!page)return <PageLoader label="Loading content"/>;if(!sections.length)return <div className="min-h-[60vh] grid place-items-center text-sm text-slate-400">This page is being prepared.</div>;const fallback=slug==='student-loans'?graduateDefaultImage.src:slug==='investments'?meetingDefaultImage.src:slug==='business-financing'?businessDefaultImage.src:slug==='personal-finance'?professionalDefaultImage.src:heroDefaultImage.src;return <div>{sections.map(s=>{const c={...(s.content||{}),imageUrl:(s.content?.imageUrl||fallback)};switch(s.section_type){case'hero':return <Hero key={s.id} c={c} bgName={s.background}/>;case'trust':return <Trust key={s.id} c={c}/>;case'split':return <div key={s.id} className={bg(s.background)}><Split c={c}/></div>;case'cards':return <div key={s.id} className={bg(s.background)}><Cards c={c}/></div>;case'features':return <div key={s.id} className={bg(s.background)}><Features c={c}/></div>;case'steps':return <Steps key={s.id} c={c}/>;case'faq':return <div key={s.id} className={bg(s.background)}><FAQ c={c}/></div>;case'cta':return <CTA key={s.id} c={c}/>;case'contact':return <div key={s.id} className={bg(s.background)}><ContactBlock c={c}/></div>;case'legal':return <div key={s.id} className={bg(s.background)}><Legal c={c}/></div>;default:return <Split key={s.id} c={c}/>}})}</div>}
