import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../../lib/supabase';
import { restoreAdminSession, signOut } from '../../lib/supabaseAuth';
import { uploadImageToCloudinary, isCloudinaryConfigured } from '../../lib/cloudinary';
import { writeAudit } from '../../lib/rbac';
import { BarChart3, BriefcaseBusiness, Check, ChevronRight, FileText, FolderOpen, Image as ImageIcon, LayoutDashboard, LockKeyhole, Mail, Menu, MessageSquare, MoreHorizontal, Plus, RefreshCw, Save, Search, Settings, ShieldCheck, Trash2, UserPlus, Users, X } from 'lucide-react';

type Tab = 'overview'|'pages'|'services'|'applications'|'messages'|'media'|'users'|'roles'|'departments'|'modules'|'settings'|'audit';

const tabs: {id:Tab;label:string;icon:React.ReactNode;permission?:string}[] = [
 {id:'overview',label:'Overview',icon:<LayoutDashboard size={18}/>},
 {id:'pages',label:'Pages & Sections',icon:<FileText size={18}/>,permission:'cms.view'},
 {id:'services',label:'Services',icon:<BriefcaseBusiness size={18}/>,permission:'services.manage'},
 {id:'applications',label:'Applications',icon:<BarChart3 size={18}/>,permission:'applications.view'},
 {id:'messages',label:'Messages',icon:<MessageSquare size={18}/>,permission:'messages.view'},
 {id:'media',label:'Media Library',icon:<ImageIcon size={18}/>,permission:'media.view'},
 {id:'users',label:'Users',icon:<Users size={18}/>,permission:'users.view'},
 {id:'roles',label:'Roles & Permissions',icon:<ShieldCheck size={18}/>,permission:'roles.manage'},
 {id:'departments',label:'Departments',icon:<FolderOpen size={18}/>,permission:'departments.manage'},
 {id:'modules',label:'Modules',icon:<MoreHorizontal size={18}/>,permission:'modules.manage'},
 {id:'settings',label:'Settings',icon:<Settings size={18}/>,permission:'settings.manage'},
 {id:'audit',label:'Audit Log',icon:<LockKeyhole size={18}/>,permission:'audit.view'},
];

const statusOptions=['NEW','REVIEWING','CONTACTED','PROCESSING','COMPLETED','DECLINED','CLOSED'];
const input='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#0d0a64] focus:ring-2 focus:ring-[#0d0a64]/10';
const card='rounded-2xl border border-slate-200 bg-white shadow-sm';

export const AdminDashboardPage: React.FC = () => {
 const navigate=useNavigate();
 const [tab,setTab]=useState<Tab>('overview');
 const [profile,setProfile]=useState<any>(null);
 const [permissions,setPermissions]=useState<Set<string>>(new Set());
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState('');
 const [mobileOpen,setMobileOpen]=useState(false);
 const [refresh,setRefresh]=useState(0);
 const can=(p?:string)=>!p||permissions.has(p)||profile?.role==='super_admin';

 useEffect(()=>{(async()=>{
   const session=await restoreAdminSession();
   if(!session){navigate('/admin/login',{replace:true});return;}
   try{
    const {data:p}=await supabase.from('profiles').select('*').eq('id',session.user.id).single();
    setProfile({...p,email:session.user.email});
    const {data:rows}=await supabase.from('user_roles').select('role_id,roles(name),role_permissions(permission_id,permissions(permission_key))').eq('user_id',session.user.id);
    const set=new Set<string>();
    (rows||[]).forEach((r:any)=>(r.role_permissions||[]).forEach((x:any)=>x.permissions?.permission_key&&set.add(x.permissions.permission_key)));
    if(p?.role==='super_admin') tabs.forEach(x=>x.permission&&set.add(x.permission));
    setPermissions(set);
   }catch(e:any){setError(e.message||'Unable to load administrator profile.');}
   finally{setLoading(false);}
 })()},[navigate,refresh]);

 if(loading) return <div className="min-h-screen grid place-items-center bg-slate-50"><div className="flex items-center gap-3 text-slate-600"><RefreshCw className="animate-spin" size={18}/> Loading administration...</div></div>;
 if(error) return <div className="min-h-screen grid place-items-center bg-slate-50 p-6"><div className={`${card} max-w-lg p-7`}><h2 className="text-xl font-bold text-slate-900">Admin access could not be loaded</h2><p className="mt-2 text-sm text-slate-600">{error}</p><button onClick={()=>setRefresh(x=>x+1)} className="mt-5 rounded-xl bg-[#0d0a64] px-4 py-2 text-sm font-semibold text-white">Retry</button></div></div>;

 const visible=tabs.filter(x=>can(x.permission));
 return <div className="min-h-screen bg-[#f6f7fb] text-slate-900">
  <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="flex h-16 items-center justify-between px-4 lg:px-6">
   <div className="flex items-center gap-3"><button className="rounded-lg p-2 lg:hidden" onClick={()=>setMobileOpen(true)}><Menu size={20}/></button><div><div className="text-sm font-bold tracking-tight">EMUNAHH-INVEST</div><div className="text-[11px] text-slate-500">Administration Console</div></div></div>
   <div className="flex items-center gap-3"><a href="/" target="_blank" className="hidden rounded-lg border px-3 py-2 text-xs font-semibold text-slate-600 sm:block">View website</a><div className="hidden text-right sm:block"><div className="text-xs font-semibold">{profile?.full_name||profile?.email}</div><div className="text-[11px] uppercase text-slate-400">{profile?.role?.replace('_',' ')}</div></div><button onClick={async()=>{await signOut();navigate('/admin/login',{replace:true})}} className="rounded-lg border border-slate-200 p-2 text-slate-600 hover:bg-slate-50" title="Sign out">↪</button></div>
  </div></header>
  <div className="flex">
   <aside className={`${mobileOpen?'fixed inset-y-0 left-0 z-50 block w-72':'hidden'} border-r border-slate-200 bg-white lg:sticky lg:top-16 lg:block lg:h-[calc(100vh-4rem)] lg:w-64 lg:shrink-0`}>
    <div className="flex h-full flex-col p-3"><div className="mb-3 flex items-center justify-between px-2 lg:hidden"><b>Menu</b><button onClick={()=>setMobileOpen(false)}><X/></button></div><nav className="space-y-1 overflow-y-auto">{visible.map(x=><button key={x.id} onClick={()=>{setTab(x.id);setMobileOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium ${tab===x.id?'bg-[#0d0a64] text-white':'text-slate-600 hover:bg-slate-100'}`}>{x.icon}<span>{x.label}</span></button>)}</nav><div className="mt-auto rounded-xl bg-slate-50 p-3 text-xs text-slate-500">Secure CMS · Supabase RBAC · Cloudinary media</div></div>
   </aside>
   <main className="min-w-0 flex-1 p-4 lg:p-7">{tab==='overview'&&<Overview/>}{tab==='pages'&&<Pages/>}{tab==='services'&&<Services/>}{tab==='applications'&&<Applications/>}{tab==='messages'&&<Messages/>}{tab==='media'&&<Media/>}{tab==='users'&&<UsersPanel/>}{tab==='roles'&&<Roles/>}{tab==='departments'&&<Departments/>}{tab==='modules'&&<Modules/>}{tab==='settings'&&<SettingsPanel/>}{tab==='audit'&&<Audit/>}</main>
  </div>
 </div>
};

const SectionTitle=({title,desc,action}:{title:string;desc?:string;action?:React.ReactNode})=><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-slate-900">{title}</h1>{desc&&<p className="mt-1 text-sm text-slate-500">{desc}</p>}</div>{action}</div>;
const Button=({children,onClick,secondary=false,type='button'}:{children:React.ReactNode;onClick?:()=>void;secondary?:boolean;type?:'button'|'submit'})=><button type={type} onClick={onClick} className={`rounded-xl px-4 py-2.5 text-sm font-semibold transition ${secondary?'border border-slate-200 bg-white text-slate-700 hover:bg-slate-50':'bg-[#0d0a64] text-white hover:opacity-95'}`}>{children}</button>;

function Overview(){const [s,setS]=useState<any>(null);useEffect(()=>{Promise.all([supabase.from('applications').select('id,status,application_type,created_at',{count:'exact'}),supabase.from('services').select('id,is_published',{count:'exact'}),supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(8)]).then(([a,sv,l])=>setS({apps:a.data||[],services:sv.data||[],logs:l.data||[]}))},[]);const cards=[['Applications',s?.apps.length||0,'All submissions'],['New',s?.apps.filter((x:any)=>x.status==='NEW').length||0,'Awaiting review'],['Published services',s?.services.filter((x:any)=>x.is_published).length||0,'Public catalogue'],['Activity',s?.logs.length||0,'Recent audit events']];return <><SectionTitle title="Overview" desc="A live operating view of the website and customer pipeline."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(c=><div className={`${card} p-5`} key={c[0] as string}><div className="text-sm text-slate-500">{c[0]}</div><div className="mt-2 text-3xl font-bold">{c[1] as number}</div><div className="mt-1 text-xs text-slate-400">{c[2]}</div></div>)}</div><div className={`${card} mt-5 p-5`}><h2 className="font-semibold">Recent activity</h2><div className="mt-4 divide-y">{(s?.logs||[]).map((x:any)=><div key={x.id} className="flex items-center justify-between py-3 text-sm"><span>{x.action}</span><span className="text-xs text-slate-400">{new Date(x.created_at).toLocaleString()}</span></div>)}{!s?.logs?.length&&<p className="py-6 text-sm text-slate-500">No audit activity yet.</p>}</div></div></>}

function Pages(){const [pages,setPages]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [sections,setSections]=useState<any[]>([]);const [saving,setSaving]=useState(false);const load=async()=>{const {data}=await supabase.from('cms_pages').select('*').order('display_order');setPages(data||[]);if(selected){const {data:s}=await supabase.from('cms_sections').select('*').eq('page_id',selected.id).order('display_order');setSections(s||[])}};useEffect(()=>{load()},[]);useEffect(()=>{if(selected) supabase.from('cms_sections').select('*').eq('page_id',selected.id).order('display_order').then(({data})=>setSections(data||[]))},[selected]);const save=async(section:any)=>{setSaving(true);await supabase.from('cms_sections').update({title:section.title,content:section.content,is_visible:section.is_visible,display_order:section.display_order}).eq('id',section.id);await writeAudit('Updated CMS section','cms_sections',section.id,{page:selected?.slug});setSaving(false)};return <><SectionTitle title="Pages & Sections" desc="Edit structured website content without touching the code."/><div className="grid gap-5 lg:grid-cols-[260px_1fr]"> <div className={`${card} p-3`}>{pages.map(p=><button key={p.id} onClick={()=>setSelected(p)} className={`mb-1 w-full rounded-xl px-3 py-3 text-left text-sm ${selected?.id===p.id?'bg-[#0d0a64] text-white':'hover:bg-slate-50'}`}><div className="font-semibold">{p.title}</div><div className={`text-xs ${selected?.id===p.id?'text-white/70':'text-slate-400'}`}>/{p.slug}</div></button>)}</div><div className={`${card} p-5`}>{!selected?<div className="grid min-h-64 place-items-center text-sm text-slate-500">Select a page to edit its sections.</div>:<><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">{selected.title}</h2><p className="text-xs text-slate-400">/{selected.slug}</p></div><Button secondary onClick={load}><RefreshCw size={15}/></Button></div>{sections.map((s,i)=><SectionEditor key={s.id} section={s} onChange={(v:any)=>setSections(prev=>prev.map(x=>x.id===s.id?v:x))} onSave={save}/>) }{!sections.length&&<p className="text-sm text-slate-500">No structured sections have been seeded for this page yet. Add sections from the CMS schema as the page is wired.</p>}</>}</div></div></>}
function SectionEditor({section,onChange,onSave}:{section:any;onChange:(x:any)=>void;onSave:(x:any)=>void}){const entries=Object.entries(section.content||{});return <div className="mb-4 rounded-2xl border border-slate-200 p-4"><div className="flex items-center justify-between"><div><div className="font-semibold">{section.title||section.section_key}</div><div className="text-xs text-slate-400">{section.section_type} · {section.section_key}</div></div><label className="text-xs"><input type="checkbox" checked={section.is_visible} onChange={e=>onChange({...section,is_visible:e.target.checked})}/> visible</label></div><div className="mt-4 grid gap-3 md:grid-cols-2">{entries.map(([key,value])=><label key={key} className="text-xs font-semibold text-slate-600">{key}<textarea className={`${input} mt-1 min-h-20`} value={typeof value==='string'?value:JSON.stringify(value,null,2)} onChange={e=>{let v:any=e.target.value;try{if(typeof value!=='string')v=JSON.parse(v)}catch{};onChange({...section,content:{...section.content,[key]:v}})}}/></label>)}</div><div className="mt-4 flex justify-end"><Button onClick={()=>onSave(section)}><Save size={15}/> Save section</Button></div></div>}

function Services(){const [rows,setRows]=useState<any[]>([]);const [edit,setEdit]=useState<any>(null);const load=()=>supabase.from('services').select('*').order('display_order').then(({data})=>setRows(data||[]));useEffect(load,[]);const save=async()=>{if(!edit)return;const payload={...edit,bullets:Array.isArray(edit.bullets)?edit.bullets:[],display_order:Number(edit.display_order||0)};if(edit.id) await supabase.from('services').update(payload).eq('id',edit.id);else await supabase.from('services').insert(payload);await writeAudit(edit.id?'Updated service':'Created service','services',edit.id||'',{});setEdit(null);load()};return <><SectionTitle title="Services" desc="Manage the services displayed across the public website." action={<Button onClick={()=>setEdit({slug:'new-service',title:'',category:'supporting',tagline:'',description:'',bullets:[],is_published:true,display_order:rows.length+1})}><Plus size={15}/> New service</Button>}/>{edit&&<div className={`${card} mb-5 p-5`}><div className="grid gap-3 md:grid-cols-2">{['title','slug','tagline','description','image_url'].map(k=><label className="text-xs font-semibold" key={k}>{k}<input className={`${input} mt-1`} value={edit[k]||''} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></label>)}<label className="text-xs font-semibold">Category<select className={`${input} mt-1`} value={edit.category} onChange={e=>setEdit({...edit,category:e.target.value})}><option>featured</option><option>supporting</option></select></label><label className="text-xs font-semibold">Published<select className={`${input} mt-1`} value={String(edit.is_published)} onChange={e=>setEdit({...edit,is_published:e.target.value==='true'})}><option value="true">Yes</option><option value="false">No</option></select></label><label className="text-xs font-semibold md:col-span-2">Bullets (one per line)<textarea className={`${input} mt-1 min-h-28`} value={(edit.bullets||[]).join('\n')} onChange={e=>setEdit({...edit,bullets:e.target.value.split('\n').filter(Boolean)})}/></label></div><div className="mt-4 flex gap-2"><Button onClick={save}><Save size={15}/> Save</Button><Button secondary onClick={()=>setEdit(null)}>Cancel</Button></div></div>}<div className="grid gap-3">{rows.map(r=><div key={r.id} className={`${card} flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between`}><div><div className="font-semibold">{r.title}</div><div className="text-xs text-slate-500">/{r.slug} · {r.is_published?'Published':'Hidden'}</div></div><div className="flex gap-2"><Button secondary onClick={()=>setEdit({...r})}>Edit</Button><button className="rounded-xl border border-red-100 p-2 text-red-600" onClick={async()=>{if(confirm('Delete this service?')){await supabase.from('services').delete().eq('id',r.id);load()}}}><Trash2 size={16}/></button></div></div>)}</div></>}

function Applications(){const [rows,setRows]=useState<any[]>([]);const [q,setQ]=useState('');const load=()=>supabase.from('applications').select('*').order('created_at',{ascending:false}).then(({data})=>setRows(data||[]));useEffect(load,[]);const filtered=useMemo(()=>rows.filter(r=>`${r.full_name} ${r.email} ${r.phone} ${r.reference} ${r.application_type}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);return <><SectionTitle title="Applications" desc="Loan, investment, business and other submitted requests."/><div className={`${card} mb-4 p-3`}><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className={`${input} pl-9`} placeholder="Search applicant, reference or type..." value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className={`${card} overflow-x-auto`}><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Applicant</th><th>Reference</th><th>Type</th><th>Status</th><th>Date</th></tr></thead><tbody>{filtered.map(r=><tr className="border-t" key={r.id}><td className="p-4"><b>{r.full_name}</b><div className="text-xs text-slate-500">{r.email} · {r.phone}</div></td><td>{r.reference}</td><td>{r.application_type}</td><td><select className="rounded-lg border px-2 py-1 text-xs" value={r.status} onChange={async e=>{await supabase.from('applications').update({status:e.target.value}).eq('id',r.id);await writeAudit('Updated application status','applications',r.id,{status:e.target.value});load()}}>{statusOptions.map(s=><option key={s}>{s}</option>)}</select></td><td>{new Date(r.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>{!filtered.length&&<div className="p-8 text-center text-sm text-slate-500">No applications found.</div>}</div></>}

function Messages(){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from('applications').select('*').eq('application_type','general_enquiry').order('created_at',{ascending:false}).then(({data})=>setRows(data||[]))},[]);return <><SectionTitle title="Messages" desc="Contact and general enquiries submitted from the public site."/><div className="space-y-3">{rows.map(r=><div className={`${card} p-5`} key={r.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><b>{r.full_name}</b><div className="text-xs text-slate-500">{r.email} · {r.phone} · {r.reference}</div></div><select className="rounded-lg border px-2 py-1 text-xs" value={r.status} onChange={async e=>{await supabase.from('applications').update({status:e.target.value}).eq('id',r.id);setRows(x=>x.map(a=>a.id===r.id?{...a,status:e.target.value}:a))}}>{statusOptions.map(s=><option key={s}>{s}</option>)}</select></div><p className="mt-3 whitespace-pre-wrap text-sm text-slate-700">{r.details?.message||r.details?.details||''}</p></div>)}{!rows.length&&<div className={`${card} p-8 text-center text-sm text-slate-500`}>No messages yet.</div>}</div></>}

function Media(){const [rows,setRows]=useState<any[]>([]);const [busy,setBusy]=useState(false);const load=()=>supabase.from('media').select('*').order('created_at',{ascending:false}).then(({data})=>setRows(data||[]));useEffect(load,[]);const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const r=await uploadImageToCloudinary(file,'emunahh-invest/media');const {data:{user}}=await supabase.auth.getUser();await supabase.from('media').insert({filename:file.name,storage_path:r.public_id,public_url:r.secure_url,title:file.name,alt_text:file.name.replace(/\.[^.]+$/,''),category:'general',mime_type:file.type,file_size:r.bytes||file.size,width:r.width,height:r.height,uploaded_by:user?.id,provider:'cloudinary',provider_public_id:r.public_id,folder:r.folder||'emunahh-invest/media'});await writeAudit('Uploaded media','media',r.public_id,{filename:file.name});load()}catch(err:any){alert(err.message||'Upload failed.')}finally{setBusy(false);e.target.value=''}};return <><SectionTitle title="Media Library" desc="Cloudinary stores the image; Supabase stores its searchable CMS record." action={<label className={`cursor-pointer rounded-xl bg-[#0d0a64] px-4 py-2.5 text-sm font-semibold text-white ${busy?'opacity-50':''}`}>{busy?'Uploading...':'Upload image'}<input hidden type="file" accept="image/*" disabled={busy} onChange={upload}/></label>}/>{!isCloudinaryConfigured()&&<div className="mb-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Cloudinary is not configured yet. Add <b>VITE_CLOUDINARY_CLOUD_NAME</b> and <b>VITE_CLOUDINARY_UPLOAD_PRESET</b> to Vercel.</div>}<div className="grid grid-cols-2 gap-4 sm:grid-cols-3 xl:grid-cols-4">{rows.map(r=><div className={`${card} overflow-hidden`} key={r.id}><img src={r.public_url} className="aspect-[4/3] w-full object-cover"/><div className="p-3"><div className="truncate text-sm font-semibold">{r.title}</div><div className="mt-1 text-[11px] text-slate-400">{r.provider} · {r.category}</div><button className="mt-3 text-xs font-semibold text-red-600" onClick={async()=>{if(confirm('Remove this media record?')){await supabase.from('media').delete().eq('id',r.id);load()}}}>Delete record</button></div></div>)}</div></>}

function UsersPanel(){const [rows,setRows]=useState<any[]>([]);const [newUser,setNewUser]=useState({email:'',password:'',full_name:'',role:'staff'});const [busy,setBusy]=useState(false);const load=()=>fetch('/api/admin/users',{headers:{Authorization:`Bearer ${localStorage.getItem('sb-access-token')||''}`}}).then(r=>r.ok?r.json():{users:[]}).then(x=>setRows(x.users||[]));useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session)localStorage.setItem('sb-access-token',data.session.access_token);load()})},[]);const create=async()=>{setBusy(true);try{const {data:{session}}=await supabase.auth.getSession();const r=await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token}`},body:JSON.stringify(newUser)});const d=await r.json();if(!r.ok)throw new Error(d.error);setNewUser({email:'',password:'',full_name:'',role:'staff'});load()}catch(e:any){alert(e.message)}finally{setBusy(false)}};return <><SectionTitle title="Users" desc="Create and manage administrative accounts."/><div className={`${card} mb-5 p-5`}><div className="grid gap-3 md:grid-cols-4"><input className={input} placeholder="Full name" value={newUser.full_name} onChange={e=>setNewUser({...newUser,full_name:e.target.value})}/><input className={input} placeholder="Email" value={newUser.email} onChange={e=>setNewUser({...newUser,email:e.target.value})}/><input className={input} type="password" placeholder="Temporary password" value={newUser.password} onChange={e=>setNewUser({...newUser,password:e.target.value})}/><select className={input} value={newUser.role} onChange={e=>setNewUser({...newUser,role:e.target.value})}><option>staff</option><option>editor</option><option>admin</option></select></div><div className="mt-3"><Button onClick={create}>{busy?'Creating...':<><UserPlus size={15}/> Create user</>}</Button></div></div><div className={`${card} overflow-x-auto`}><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Name</th><th>Email</th><th>Role</th><th>Created</th></tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r.id}><td className="p-4">{r.full_name||'—'}</td><td>{r.email}</td><td className="uppercase">{r.role}</td><td>{r.created_at?new Date(r.created_at).toLocaleDateString():''}</td></tr>)}</tbody></table></div></>}

function Roles(){const [roles,setRoles]=useState<any[]>([]);const [perms,setPerms]=useState<any[]>([]);const [map,setMap]=useState<Record<string,string[]>>({});const load=async()=>{const [{data:r},{data:p},{data:rp}]=await Promise.all([supabase.from('roles').select('*').order('name'),supabase.from('permissions').select('*').order('module_key,permission_key'),supabase.from('role_permissions').select('*')]);setRoles(r||[]);setPerms(p||[]);const m:any={};(rp||[]).forEach((x:any)=>(m[x.role_id]??=[]).push(x.permission_id));setMap(m)};useEffect(()=>{load()},[]);const toggle=async(role:any,p:any)=>{const current=map[role.id]||[];if(current.includes(p.id)){await supabase.from('role_permissions').delete().match({role_id:role.id,permission_id:p.id});setMap({...map,[role.id]:current.filter(x=>x!==p.id)})}else{await supabase.from('role_permissions').insert({role_id:role.id,permission_id:p.id});setMap({...map,[role.id]:[...current,p.id]})}};return <><SectionTitle title="Roles & Permissions" desc="Granular access control by role and module."/><div className={`${card} overflow-x-auto`}><table className="w-full min-w-[900px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Permission</th>{roles.map(r=><th key={r.id} className="p-4">{r.name}</th>)}</tr></thead><tbody>{perms.map(p=><tr className="border-t" key={p.id}><td className="p-4"><b>{p.label}</b><div className="text-xs text-slate-400">{p.permission_key}</div></td>{roles.map(r=><td className="p-4" key={r.id}><input type="checkbox" disabled={r.name==='super_admin'} checked={(map[r.id]||[]).includes(p.id)} onChange={()=>toggle(r,p)}/></td>)}</tr>)}</tbody></table></div></>}

function Departments(){const [rows,setRows]=useState<any[]>([]);const [name,setName]=useState('');const load=()=>supabase.from('departments').select('*').order('name').then(({data})=>setRows(data||[]));useEffect(load,[]);return <><SectionTitle title="Departments" desc="Organize administrative users and responsibilities."/><div className={`${card} mb-5 flex gap-2 p-4`}><input className={input} placeholder="Department name" value={name} onChange={e=>setName(e.target.value)}/><Button onClick={async()=>{if(!name.trim())return;await supabase.from('departments').insert({name});setName('');load()}}><Plus size={15}/> Add</Button></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rows.map(r=><div className={`${card} p-4`} key={r.id}><div className="font-semibold">{r.name}</div><p className="mt-1 text-sm text-slate-500">{r.description||'No description.'}</p></div>)}</div></>}

function Modules(){const [rows,setRows]=useState<any[]>([]);const load=()=>supabase.from('modules').select('*').order('display_order').then(({data})=>setRows(data||[]));useEffect(load,[]);return <><SectionTitle title="Modules" desc="Switch optional functions on or off without rewriting the website."/><div className="grid gap-3 md:grid-cols-2">{rows.map(r=><div className={`${card} flex items-center justify-between p-5`} key={r.id}><div><div className="font-semibold">{r.name}</div><p className="mt-1 text-sm text-slate-500">{r.description}</p></div><button disabled={r.is_system} onClick={async()=>{await supabase.from('modules').update({is_enabled:!r.is_enabled}).eq('id',r.id);load()}} className={`relative h-7 w-12 rounded-full ${r.is_enabled?'bg-[#0d0a64]':'bg-slate-300'} ${r.is_system?'opacity-60':''}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${r.is_enabled?'left-6':'left-1'}`}/></button></div>)}</div></>}

function SettingsPanel(){const [row,setRow]=useState<any>({});const [global,setGlobal]=useState<any>({});useEffect(()=>{Promise.all([supabase.from('site_settings').select('*').eq('id',1).maybeSingle(),supabase.from('cms_global_settings').select('*').eq('id',1).maybeSingle()]).then(([a,g])=>{setRow(a.data||{});setGlobal(g.data||{})})},[]);return <><SectionTitle title="Settings" desc="Company details, branding and global CMS settings."/><div className={`${card} p-5`}><div className="grid gap-4 md:grid-cols-2">{['company_name','company_email','notification_email','phone','secondary_phone','whatsapp','office_address','email_sender_name','reply_to_email','website_url','logo_url'].map(k=><label key={k} className="text-xs font-semibold">{k.replaceAll('_',' ')}<input className={`${input} mt-1`} value={row[k]||''} onChange={e=>setRow({...row,[k]:e.target.value})}/></label>)}</div><div className="mt-5"><Button onClick={async()=>{await supabase.from('site_settings').upsert({...row,id:1});await writeAudit('Updated settings','site_settings','1',{});alert('Settings saved.')}}><Save size={15}/> Save settings</Button></div></div><div className={`${card} mt-5 p-5`}><h2 className="font-semibold">Global CMS JSON</h2><p className="mt-1 text-sm text-slate-500">Advanced structured settings for header, footer, branding and SEO. No source code is required.</p><textarea className={`${input} mt-4 min-h-72 font-mono text-xs`} value={JSON.stringify({header:global.header||{},footer:global.footer||{},branding:global.branding||{},seo:global.seo||{}},null,2)} onChange={e=>{try{setGlobal({...global,...JSON.parse(e.target.value)})}catch{}}}/><div className="mt-3"><Button onClick={async()=>{await supabase.from('cms_global_settings').upsert({id:1,header:global.header||{},footer:global.footer||{},branding:global.branding||{},seo:global.seo||{}});await writeAudit('Updated global CMS settings','cms_global_settings','1',{});alert('Global settings saved.')}}><Save size={15}/> Save global settings</Button></div></div></>}

function Audit(){const [rows,setRows]=useState<any[]>([]);useEffect(()=>{supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(200).then(({data})=>setRows(data||[]))},[]);return <><SectionTitle title="Audit Log" desc="Security and administrative activity history."/><div className={`${card} overflow-x-auto`}><table className="w-full min-w-[800px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-4">Action</th><th>Entity</th><th>Actor</th><th>Time</th></tr></thead><tbody>{rows.map(r=><tr className="border-t" key={r.id}><td className="p-4">{r.action}</td><td>{r.entity_type} {r.entity_id}</td><td>{r.actor_id||'system'}</td><td>{new Date(r.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></>}
